# Generated by Django 6.0.2 on 2026-04-17 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='price_per_kilo',
        ),
        migrations.AddField(
            model_name='laundryshop',
            name='contact_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laundryshop',
            name='shop_address',
            field=models.CharField(default='default address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laundryshop',
            name='shop_manager',
            field=models.CharField(default='manager', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laundrytype',
            name='washing_instructions',
            field=models.CharField(default='standard wash', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='estimated_time',
            field=models.CharField(default='1 hour', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_category',
            field=models.CharField(default='standard', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.laundryshop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
