# Generated by Django 6.0.2 on 2026-06-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_price_service_price_per_kilo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryshop',
            name='contact_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='laundryshop',
            name='shop_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
