# Generated by Django 6.0.4 on 2026-06-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('laundry_shop', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('Wash Only', 'Wash Only'), ('Wash & Dry', 'Wash & Dry'), ('Wash, Dry & Fold', 'Wash, Dry & Fold'), ('Dry Cleaning', 'Dry Cleaning')], max_length=50)),
                ('laundry_type', models.CharField(choices=[('Regular Clothes', 'Regular Clothes'), ('Bedsheets', 'Bedsheets'), ('Blankets', 'Blankets'), ('Curtains', 'Curtains'), ('Delicates', 'Delicates')], max_length=50)),
                ('weight_in_kilos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('promo_code', models.CharField(blank=True, max_length=20, null=True)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('delivery_address', models.TextField()),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('GCash', 'GCash'), ('Credit Card', 'Credit Card')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rider Assigned', 'Rider Assigned'), ('Picked Up', 'Picked Up'), ('In Laundry Process', 'In Laundry Process'), ('Ready for Delivery', 'Ready for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
