# Generated by Django 6.0.4 on 2026-06-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='laundry_shop',
            field=models.CharField(choices=[('Clean Wash Laundry', 'Clean Wash Laundry'), ('Fresh Fold Laundry', 'Fresh Fold Laundry'), ('LABABA Laundry Shop', 'LABABA Laundry Shop')], max_length=100),
        ),
    ]
