# Generated by Django 6.0.4 on 2026-06-15 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_customer_name_order_customer_and_more'),
        ('shop', '0001_initial'),
    ]

    operations = []
